# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3d42329fb08433c9b4c8cc09263c22531ae0304d776d3d02c89c4c97c526369e230677e9c41faf2846c138808f68b12763573791937660a7517963c31029b02

test:
  secret_key_base: 3b652380edb7e0abf73e741b22a2e9e8c700a7cc555a93e8ed8e2292a5649bbe251d383535f3a52df272488cc16d5d91b91d83898ade0a9184a225f2845053ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
